# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  pull_request:
    branches: [ "main" ]
env:
    AWS_ACCESS_KEY: ${{secrets.AWS_ACCESS_KEY}}
    AWS_SECRET_ACCESS_KEY: ${{secrets_AWS_SECRET_ACCESS_KEY}}
jobs:
  build:

    runs-on: ubuntu-latest
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Run `packer init`
        id: init
        run: "packer init ./packer/webapp.pkr.hcl"

      - name: Run `packer validate`
        id: validate
        run: "packer validate ./packer/webapp.pkr.hcl"

      - run: npm ci 
      - run: npm test
