name: Packer

on:
  pull_request:
    branches: [ "main" ]
    types:
      - closed
env:
    AWS_ACCESS_KEY: ${{secrets.AWS_ACCESS_KEY}}
    AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
jobs:
  
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Zip webapp  
        run: | 
          cd ..
          zip -r webapp.zip webapp/
          cd webapp
          ls -al
          sleep 10
          
      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        
      - name: Run `packer init`
        run: packer init ./packer/webapp.pkr.hcl

      - name: Build `AMI`
        run: packer build ./packer/webapp.pkr.hcl
      
    